## Intro to NumPy for Linear Algebra

### Why NumPy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy is easy to `import` and comes standard when you downloaded Anaconda. Simply write `import numpy as np` to make the package available in your current notebook. We are going to alias NumPy as `np` to make it easier to use when calling the different functions of the package

#### References
- [Linear Algebra](https://en.wikipedia.org/wiki/Linear_algebra)
- [NumPy API Docs](https://numpy.org/doc/1.20/reference/index.html)
- [NumPy Reference Docs](https://numpy.org/doc/stable/numpy-ref.pdf)
![NumPy Cheat Sheet](img/Numpy_Python_Cheat_Sheet.jpg)

In [17]:
# Importing numpy
import numpy as np

### Scalars

[Scalar Reference](https://en.wikipedia.org/wiki/Scalar_(mathematics))

Scalars are real numbers used in linear algebra.

In [18]:
# Scalar Example

scalar = 2
vector = np.array([5,10])

print(scalar*vector)

[10 20]


In [19]:
[10, 20] + 2

TypeError: can only concatenate list (not "int") to list

In [21]:
np.array([10,20])/2

array([ 5., 10.])

### Vectors

[Vector Reference](https://en.wikipedia.org/wiki/Vector_space)

Vectors are an ordered list of elements and differs from a scalar by having both **magnitude** and **direction**.

In [3]:
# 1 dimmensional vector
print("1 Dimmensional Vector: \n",np.array([1]))

# 2 dimmensional vector
print("2 Dimmensional Vector: \n",np.array([[1],
                                         [2]]))

# 3 dimmensional vector
print("3 Dimmensional Vector: \n",np.array([[1],
                                         [2],
                                         [3]]))

1 Dimmensional Vector: 
 [1]
2 Dimmensional Vector: 
 [[1]
 [2]]
3 Dimmensional Vector: 
 [[1]
 [2]
 [3]]


### Norm

- [Reference](https://en.wikipedia.org/wiki/Norm_(mathematics))
- [Documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)

![img](https://wikimedia.org/api/rest_v1/media/math/render/svg/4d2562bd8e6df0c2625fd9c0e0c09ee9b932785d)

Norm is also know as the magnitude of the vector.

In [4]:
# Create vector
v = np.array([3,4,5,6,7])
np.linalg.norm(v)

# Calculating norm by hand
hand_norm = np.sqrt(np.sum(np.power(v,2)))
print("Norm by hand:",hand_norm)

# Using NumPy to calculate norm
numpy_norm = np.linalg.norm(v)
print("Norm using NumPy:",numpy_norm)

Norm by hand: 11.61895003862225
Norm using NumPy: 11.61895003862225


In [24]:
np.product(v)

2520

### Dot Product

- [Reference](https://en.wikipedia.org/wiki/Dot_product)
- [Documentation](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

**Formula:**

![img](https://wikimedia.org/api/rest_v1/media/math/render/svg/5bd0b488ad92250b4e7c2f8ac92f700f8aefddd5)

**Example:**

![img](https://wikimedia.org/api/rest_v1/media/math/render/svg/be560d2c22a074c7711ae946954725d31ec77928)

In [26]:
# Make vectors
price = np.array([1,2,3,4])
shares = np.array([5,6,7,8])*100

# Compute dot product by hand
# hand_dot = np.sum(v1*v2)
# print("Dot product by hand:", hand_dot)

# Compute dot product using NumPy
numpy_dot = np.dot(price, shares)
print(f"Prices: {price}")
print(f"Shares: {shares}")
print("Total transaction value:", numpy_dot)

Prices: [1 2 3 4]
Shares: [500 600 700 800]
Total transaction value: 7000


### Matrices

- [Reference](https://en.wikipedia.org/wiki/Matrix_(mathematics)#Definitions_and_notations)

Matrices can be easily made by making a list of lists withing a `np.array`

In [28]:
#Example Matrix

matrix = np.matrix(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Matrix Equality

- [Documentation](https://numpy.org/doc/stable/reference/generated/numpy.array_equal.html)

Matrices are equal if their shape and elements are the same

In [37]:
m1 = np.array(
    [
        [1,2,3],
        [3,2,1]
    ]
)

m2 = np.array(
    [
        [1,2,3],
        [3,2,5]
    ]
)


# Matrix equality using NumPy
np.array_equal(m1, m2)
m1 == m2
(m1 == m2).all()

False

### Transpose

- [Reference](https://en.wikipedia.org/wiki/Transpose)
- [Documentation](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)

![](https://upload.wikimedia.org/wikipedia/commons/e/e4/Matrix_transpose.gif)

In [8]:
m1 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

# Transpose using NumPy
np.transpose(m1)

array([[1, 4],
       [2, 5],
       [3, 6]])

### Square Matrices

- [Reference](https://en.wikipedia.org/wiki/Square_matrix)

![](https://upload.wikimedia.org/wikipedia/commons/b/bf/Arbitrary_square_matrix.gif)

A square matrix was the same number of rows as columns

**Special Kind of Square Matrix (Identity Matrix)**

An identity matrix has 1 values across the diagonal and a zero for all other values. When multiplying a matrix by an identity matrix it is equvalent to multiplying a number 1 (The value returns itself). Some examples are shown below

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/2c1a08c2710bc572d6ce5327a6094f34c76ebcc8)

In [9]:
# Square Matrix example using NumPy

m1 = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

# Check to see if rows equals columns
square_numpy = m1.shape
print("Check shape of matrix:\n", square_numpy)

m_identity = np.array(
    [
        [1,0,0],
        [0,1,0],
        [0,0,1]
        
    ]
)

# Multiply m1 by identity matrix to produce m1
identity_result = m1.dot(m_identity)
print("\nResult of Identity multiplied by target matrix:\n", identity_result)

Check shape of matrix:
 (3, 3)

Result of Identity multiplied by target matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Determinant

- [Reference](https://en.wikipedia.org/wiki/Determinant)
- [Documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html)

The determinant of a matrix is used to find the inverse of a matrix. The calculation is easy to understand for a 2X2 matrix and gets more complicated for larger square matrixes.

**Determinant of 2X2 Matrix**

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/5b2e40d390e1d26039aabee44c7d1d86c8755232)

**Determinant of 3X3 Matrix**

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/a891ca1b518ba39ff21a458c74f9cc74bcefb18c)

In [10]:
m1 = np.array(
    [
        [1,2],
        [3,4]
    ]
)

# Calculating determinant by hand
a = m1[0][0]
b = m1[0][1]
c = m1[1][0]
d = m1[1][1]

hand_det = a*d - b*c
print("Determinant by hand:" ,hand_det)

# Determinant using NumPy
numpy_det = np.linalg.det(m1)
print("Determinant using NumPy:", numpy_det)

Determinant by hand: -2
Determinant using NumPy: -2.0000000000000004


### Inverse

- [Reference](https://en.wikipedia.org/wiki/Invertible_matrix)
- [Documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)

In linear algebra, an n-by-n square matrix A is called invertible (also nonsingular or nondegenerate), if there exists an n-by-n square matrix B such that

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/3292afbdf0bc47ee682fc420a0bb4bf8761e6ae7)

where **I** is the identity matrix.

![](https://www.mathsisfun.com/algebra/images/matrix-inverse-2x2.svg)

In [11]:
m1 = np.array(
    [
        [1,2],
        [3,4]
    ]
)

# Calculating Inverse by hand
a = m1[0][0]
b = m1[0][1]
c = m1[1][0]
d = m1[1][1]

# Calculate determinant
hand_det = a*d - b*c
print("Determinant:", hand_det, "\n")

# Create transformed array according to formula above
m1_adj = np.array(
    [
        [4,-2],
        [-3,1]
    ]
)

# Calculate square matrix with determinant and transformed array
m1_square = m1_adj.dot((1/hand_det))
print("Calculated Square Matrix using Determinant by hand:\n", m1_square, "\n")

# Multiply m1_square by original matrix to see if it equals the identity matrix
hand_inv = m1.dot(m1_square)
print("Results of Inverse by hand:\n", hand_inv, "\n")

# Calculate Inverse using NumPy
numpy_inv = np.linalg.inv(m1)
print("Numpy Calculated Inverse:\n", numpy_inv, "\n")

numpy_identity = m1.dot(numpy_inv)
print("Results of Inverse using NumPy:\n", numpy_identity)

Determinant: -2 

Calculated Square Matrix using Determinant by hand:
 [[-2.   1. ]
 [ 1.5 -0.5]] 

Results of Inverse by hand:
 [[1. 0.]
 [0. 1.]] 

Numpy Calculated Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]] 

Results of Inverse using NumPy:
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


### Linear System of Equations

In mathematics, a system of linear equations (or linear system) is a collection of one or more linear equations involving the same set of variables.

- [Reference](https://en.wikipedia.org/wiki/System_of_linear_equations)
- [The Math Behind how It's Solved](https://www.mathsisfun.com/algebra/systems-linear-equations-matrices.html)

**Example**

- 4x  + 3y = 20
- -5x + 9y = 26

In [12]:
# Represent coefficients in a numPy array
A = np.array([[ 4, 3],
             [-5, 9]])

# Requirements
B = np.array([[20],
             [26]])

In [13]:
# Solve the problem
X = np.linalg.inv(A).dot(B)
X

array([[2.],
       [4.]])

In [14]:
# Plug in results
x = X[0][0]
y = X[1][0]

In [15]:
# Check 4x + 3y = 20
4*x + 3*y

20.0

In [16]:
# Check -5x + 9y = 26
-5*x + 9*y

25.999999999999993